# Generated by Django 4.2.30 on 2026-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='best_season',
            field=models.CharField(blank=True, default='Oct – Mar', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='packing_tips',
            field=models.TextField(blank=True, default='Comfortable walking shoes, camera, power bank, light jacket'),
        ),
        migrations.AddField(
            model_name='city',
            name='weather_condition',
            field=models.CharField(blank=True, default='Sunny & Pleasant', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='weather_temp',
            field=models.CharField(blank=True, default='24°C', max_length=50),
        ),
    ]
